baseurl = "http://kicad-pcb.org/"
languageCode = "en-us"
title = "KiCad EDA"
canonifyurls = true
layoutdir = "layouts"
pluralizelisttitles = false

[params]
	DateForm = "2006-01-02"
	Description = "A Cross Platform and Open Source Electronics Design Automation Suite"
	Author = "The KiCad editors"
	Forum = "https://forum.kicad.info/"
	Ganalytics = "UA-3810500-6"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/kicad_pcb"
[[params.social]]
  title = "github"
  url = "https://github.com/KiCad"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/kicadpcb"

[[menu.main]]
    name   = "Blog"
    url    = "/post/"
    weight = -200

[[menu.main]]
    name   = "Download"
    url    = "/download/"
    weight = 600

[[menu.main]]
    name   = "Contribute"
    weight = 500

[[menu.main]]
    name   = "Community"
    weight = 10
[[menu.main]]
    parent = "Community"
    name   = "User Forum"
    url    = "http://forum.kicad.info/"
    weight = 10
[[menu.main]]
    parent = "Community"
    name   = "User Mailing List"
    url    = "http://groups.yahoo.com/group/kicad-users/"
    weight = 15
[[menu.main]]
    parent = "Community"
    name   = "kicad.jp"
    url    = "http://kicad.jp/"
    weight = 20

[[menu.main]]
    parent = "Discover"
    name   = "Made With Kicad"
    url    = "/made-with-kicad/"
    weight = 20

[[menu.main]]
    name   = "Help"
    weight = 0
